# 熔断时间5秒
hystrix:
  command:
    #service-implement服务超时时间
    service-implement:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
spring:
  redis:
    host: 192.168.0.61
    port: 6379
  cloud:
    gateway:
      locator:
        enabled: true
      discovery:
        locator:
          #支持小写服务id
          lower-case-service-id: true
      routes:
        - id: limit_route
          uri: lb://service-implement
          predicates:
            - Path=/api-c/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
            - RewritePath=/api-c/(?<segment>.*), /$\{segment}
            # 降级配置
            - name: Hystrix
              args:
                name: default
                fallbackUri: 'forward:/defaultFallback'
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG